binance:
  api:
    key: IRaEnilNIA2oiwoHKVeHfp7YlRba0gW2EUTkukS42SUrJK8OPQDfKeQsroUi4aEn
    secret: 7mSSfpiAFsRl8Hm9AjHe771077IA0RB3D2qcBbzpz1JGtUxlEp1Li1ayaPUf65a7

spring:
  application:
    name: cryptora-analyze-service

  datasource:
    url: jdbc:mysql://localhost:3306/binance
    username: root
    password: gustavo
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.MySQL8Dialect
  ai:
    ollama:
      base-url: http://172.27.156.127
      init:
        pull-model-strategy: WHEN_MISSING
      chat:
        model: qwen2.5:1.5b
        options:
          temperature: 0.6
          max-tokens: 200
          top-p: 0.9

cryptora:
  short:
    time:
      period: 50
  long:
    time:
      period: 200
  atr:
    period: 14
    multiplier: 2.0
  enter:
    price: 0.997
#min spread
  exit:
    price: 1.003
# min margin
    strategy:
      percentage: 0.7
#sale to zero
  panic:
    sell:
      param: 5
  buy:
    quantity: 0.001
#current budget
  enough: 
    asset:
      balance: 40
  current: 
    trade:
      pair: BTCUSDT
    coin: BTC

server:
  port: 8088